server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "30s"

mcp:
  version: "2024-11-05"
  name: "mcp-gateway"
  description: "MCP Remote Server Gateway"
  
  capabilities:
    tools:
      list_changed: false
    resources:
      subscribe: false
      list_changed: false
    logging:
      level: "info"

# Gateway configuration
gateway:
  connection_timeout: "30s"
  request_timeout: "30s"
  retry_attempts: 3
  retry_delay: "1s"
  enable_health_check: true
  health_check_interval: "60s"
  # Note: Upstream servers are now managed dynamically via the CRUD API
  # Use the /api/upstream-servers endpoints to manage upstream MCP servers

security:
  enable_auth: true
  api_keys: []
  allowed_ips: []

logging:
  level: "info"
  format: "json"
  output: "stdout"
  rotation:
    enabled: true
    max_size_mb: 10       # Maximum size of each log file in MB
    max_backups: 3        # Maximum number of backup files to keep
    max_age_days: 30      # Maximum number of days to keep old log files
    compress: true        # Whether to compress rotated log files
