server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "30s"

mcp:
  version: "2024-11-05"
  name: "mcp-gateway"
  description: "MCP Remote Server Gateway"
  
  # Local tools configuration (optional - gateway can also serve local tools)
  tools:
    - name: "echo"
      description: "Echo back the provided text"
      input_schema:
        type: "object"
        properties:
          text:
            type: "string"
            description: "Text to echo back"
        required: ["text"]
    
    - name: "get_time"
      description: "Get current time"
      input_schema:
        type: "object"
        properties: {}
  
  # Local resources configuration (optional)
  resources:
    - uri: "file://example.txt"
      name: "Example File"
      description: "An example text file"
      mime_type: "text/plain"
    
    - uri: "data://config"
      name: "Configuration"
      description: "Server configuration data"
      mime_type: "application/json"
  

  
  capabilities:
    tools:
      list_changed: false
    resources:
      subscribe: false
      list_changed: false
    logging:
      level: "info"

# Gateway configuration
gateway:
  connection_timeout: "30s"
  request_timeout: "30s"
  retry_attempts: 3
  retry_delay: "1s"
  enable_health_check: true
  health_check_interval: "60s"
  # Note: Upstream servers are now managed dynamically via the CRUD API
  # Use the /api/upstream-servers endpoints to manage upstream MCP servers

security:
  enable_auth: false
  api_keys: []
  allowed_ips: []

logging:
  level: "info"
  format: "json"
  output: "stdout"
